[build]
  publish = "out"
  functions = "src/functions"
  command = "npm run export"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
  
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''
